# Generated by Django 4.0.4 on 2023-04-02 18:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainSite', '0002_remove_retrivetype_transport_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
            },
        ),
        migrations.CreateModel(
            name='Transport_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Тип транспорта',
                'verbose_name_plural': 'Типы транспорта',
            },
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('capacity', models.FloatField(blank=True, null=True, verbose_name='Грузоподъёмность')),
                ('price', models.FloatField(verbose_name='Время доставки')),
                ('transport_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainSite.transport_type', verbose_name='Тип транспорта')),
            ],
            options={
                'verbose_name': 'Машина',
                'verbose_name_plural': 'Машины',
            },
        ),
        migrations.CreateModel(
            name='RetriveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Наименование')),
                ('descripton', models.TextField(verbose_name='Описание')),
                ('delivery_time', models.IntegerField(verbose_name='Время доставки')),
                ('added_price', models.IntegerField(default=0, verbose_name='Добавочная стоимость')),
                ('transport_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainSite.transport_type', verbose_name='Тип транспорта')),
            ],
            options={
                'verbose_name': 'Тип отправления',
                'verbose_name_plural': 'Типы отправления',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Имя')),
                ('second_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, max_length=50, null=True, verbose_name='Отчество')),
                ('weigth', models.FloatField(blank=True, null=True, verbose_name='Вес')),
                ('retrive_address', models.TextField(verbose_name='Адрес отправки')),
                ('delivery_address', models.TextField(verbose_name='Адрес доставки')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('total_price', models.FloatField(blank=True, null=True, verbose_name='Стоимость отправки:')),
                ('retrive_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainSite.retrivetype', verbose_name='Тип транспорта')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainSite.status', verbose_name='Статус')),
                ('transport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainSite.transport', verbose_name='Транспорт')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
