# Generated by Django 4.0.4 on 2023-04-02 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='retrivetype',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/category/', verbose_name='Фото'),
        ),
    ]
