# Generated by Django 4.0.4 on 2023-04-02 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0004_retrivetype_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport',
            name='price',
            field=models.FloatField(verbose_name='Стоимость'),
        ),
    ]
