# Generated by Django 4.0.4 on 2023-04-02 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0005_alter_transport_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Груз:'),
        ),
    ]
