# Generated by Django 4.0.4 on 2023-04-02 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0007_city_alter_transport_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='transport',
            name='price',
        ),
        migrations.AlterField(
            model_name='order',
            name='weigth',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Вес'),
        ),
    ]
