# Generated by Django 4.0.4 on 2023-04-02 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0009_remove_order_transport_orderroute_transport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='weigth',
            new_name='weight',
        ),
    ]
