# Generated by Django 4.0.4 on 2023-04-02 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0010_rename_weigth_order_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderroute',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Цена'),
        ),
    ]
