# Generated by Django 4.0.4 on 2023-04-02 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0011_alter_orderroute_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderroute',
            name='price',
        ),
        migrations.AddField(
            model_name='city',
            name='delivery_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=500, max_digits=10, null=True, verbose_name='Цена'),
        ),
    ]
