# Generated by Django 4.0.4 on 2023-04-02 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0012_remove_orderroute_price_city_delivery_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='delivery_price',
        ),
        migrations.AddField(
            model_name='orderroute',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Цена'),
        ),
    ]
