# Generated by Django 4.0.4 on 2023-04-02 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0013_remove_city_delivery_price_orderroute_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retrivetype',
            name='transport_type',
        ),
        migrations.RemoveField(
            model_name='transport',
            name='transport_type',
        ),
        migrations.AddField(
            model_name='transport',
            name='retrive_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainSite.retrivetype', verbose_name='Тип транспорта'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderroute',
            name='delivery_time',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Время доставки'),
        ),
        migrations.DeleteModel(
            name='Transport_Type',
        ),
    ]
