# Generated by Django 4.0.4 on 2023-04-03 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0015_alter_transport_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Статус машрута',
                'verbose_name_plural': 'Статусы маршрутов',
            },
        ),
        migrations.AddField(
            model_name='orderroute',
            name='route_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainSite.routestatus', verbose_name='Статус маршрута'),
        ),
    ]
