# Generated by Django 4.0.4 on 2023-04-04 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0016_routestatus_orderroute_route_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Общая стоимость'),
        ),
        migrations.AddField(
            model_name='order',
            name='total_time',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Общее время доставки'),
        ),
    ]
