# Generated by Django 4.0.4 on 2023-04-04 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0017_order_total_price_order_total_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_time',
        ),
    ]
